name: pillow
description: A flutter plugin for dream project.
version: 0.0.1
homepage: xyz.sfx.plw

environment:
  sdk: ">=2.16.0 <3.0.0"

flutter:
  plugin:
    platforms:
      android:
        package: xyz.sfx.plw
        pluginClass: PillowPlugin
      ios:
        pluginClass: PillowPlugin
      macos:
        pluginClass: PillowPlugin
      windows:
        pluginClass: PillowPlugin
      linux:
        pluginClass: PillowPlugin
      web:
        pluginClass: PillowWeb
        fileName: pillow_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  ffi:
  ffigen: ^4.1.3
  js:

dev_dependencies:
  build_runner:
  flutter_lints:
  flutter_test:
    sdk: flutter

ffigen:
  name: CouchLibrary
  output: 'lib/gen/generated_bindings.dart'
  headers:
    entry-points:
      - '../couch/out/include/markdown.h'
